# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import temperatura_pb2 as temperatura__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in temperatura_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemperaturaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObterUltimoAlerta = channel.unary_unary(
                '/temperatura.TemperaturaService/ObterUltimoAlerta',
                request_serializer=temperatura__pb2.ConsultaAlertaRequest.SerializeToString,
                response_deserializer=temperatura__pb2.AlertaResponse.FromString,
                _registered_method=True)
        self.ListarAlertas = channel.unary_unary(
                '/temperatura.TemperaturaService/ListarAlertas',
                request_serializer=temperatura__pb2.ConsultaAlertaRequest.SerializeToString,
                response_deserializer=temperatura__pb2.ListaAlertasResponse.FromString,
                _registered_method=True)


class TemperaturaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObterUltimoAlerta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarAlertas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperaturaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObterUltimoAlerta': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterUltimoAlerta,
                    request_deserializer=temperatura__pb2.ConsultaAlertaRequest.FromString,
                    response_serializer=temperatura__pb2.AlertaResponse.SerializeToString,
            ),
            'ListarAlertas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarAlertas,
                    request_deserializer=temperatura__pb2.ConsultaAlertaRequest.FromString,
                    response_serializer=temperatura__pb2.ListaAlertasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperatura.TemperaturaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('temperatura.TemperaturaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TemperaturaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObterUltimoAlerta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperatura.TemperaturaService/ObterUltimoAlerta',
            temperatura__pb2.ConsultaAlertaRequest.SerializeToString,
            temperatura__pb2.AlertaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarAlertas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/temperatura.TemperaturaService/ListarAlertas',
            temperatura__pb2.ConsultaAlertaRequest.SerializeToString,
            temperatura__pb2.ListaAlertasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
