# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperatura.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'temperatura.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperatura.proto\x12\x0btemperatura\"*\n\x15\x43onsultaAlertaRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"\xa7\x01\n\x0e\x41lertaResponse\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x01\x12\x10\n\x08variacao\x18\x03 \x01(\x01\x12\x0f\n\x07unidade\x18\x04 \x01(\t\x12\x15\n\rclassificacao\x18\x05 \x01(\t\x12\x0e\n\x06\x61lerta\x18\x06 \x01(\x08\x12\x10\n\x08mensagem\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"D\n\x14ListaAlertasResponse\x12,\n\x07\x61lertas\x18\x01 \x03(\x0b\x32\x1b.temperatura.AlertaResponse2\xc2\x01\n\x12TemperaturaService\x12T\n\x11ObterUltimoAlerta\x12\".temperatura.ConsultaAlertaRequest\x1a\x1b.temperatura.AlertaResponse\x12V\n\rListarAlertas\x12\".temperatura.ConsultaAlertaRequest\x1a!.temperatura.ListaAlertasResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperatura_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTAALERTAREQUEST']._serialized_start=34
  _globals['_CONSULTAALERTAREQUEST']._serialized_end=76
  _globals['_ALERTARESPONSE']._serialized_start=79
  _globals['_ALERTARESPONSE']._serialized_end=246
  _globals['_LISTAALERTASRESPONSE']._serialized_start=248
  _globals['_LISTAALERTASRESPONSE']._serialized_end=316
  _globals['_TEMPERATURASERVICE']._serialized_start=319
  _globals['_TEMPERATURASERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
